from django.db import models

# -*- coding: utf-8 -*-
from django.utils.translation import ugettext as _

from django.db import models

from base.models import BaseModel
from kennels.models import Kennel


class Breed(BaseModel):

    DOGS_CHOICES = (
        ("affenpinscher", _("Affenpinscher")),
        ("afghan_hound", _("Afghan Hound")),
        ("atlas_mountain_dog", _("Atlas Mountain Dog")),
        ("airedale_terrier", _("Airedale Terrier")),
        ("akita", _("Akita")),
        ("alaskan_malamute", _("Alaskan Malamute")),
        ("alpine_dachsbracke", _("Alpine Dachsbracke")),
        ("american_akita", _("American Akita")),
        ("american_cocker_spaniel", _("American Cocker Spaniel")),
        ("american_foxhound", _("American Foxhound")),
        ("american_staffordshire_terrier", _("American Staffordshire Terrier")),
        ("american_water_spaniel", _("American Water Spaniel")),
        ("medium-sized_anglo-french_hound", _("Medium-sized Anglo-French Hound")),
        ("appenzell_cattle_dog", _("Appenzell Cattle Dog")),
        ("ariege_hound", _("Ariege Hound")),
        ("australian_cattle_dog", _("Australian Cattle Dog")),
        ("australian_kelpie", _("Australian Kelpie")),
        ("australian_shepherd", _("Australian Shepherd")),
        ("australian_silky_terrier", _("Australian Silky Terrier")),
        ("australian_stumpy_tail_cattle_dog", _("Australian Stumpy Tail Cattle Dog")),
        ("australian_terrier", _("Australian Terrier")),
        ("azawakh", _("Azawakh")),
        ("french_water_dog", _("French Water Dog")),
        ("basenji", _("Basenji")),
        ("artesian-norman_basset", _("Artesian-Norman Basset")),
        ("blue_gascony_basset", _("Blue Gascony Basset")),
        ("fawn_brittany_basset", _("Fawn Brittany Basset")),
        ("basset_hound", _("Basset Hound")),
        ("bavarian_mountain_scenthound", _("Bavarian Mountain Scenthound")),
        ("beagle", _("Beagle")),
        ("beagle-harrier", _("Beagle-Harrier")),
        ("bearded_collie", _("Bearded Collie")),
        ("bedlington_terrier", _("Bedlington Terrier")),
        ("white_swiss_shepherd_dog", _("White Swiss Shepherd Dog")),
        ("beauceron", _("Beauceron")),
        ("briard", _("Briard")),
        ("picardy_sheepdog", _("Picardy Sheepdog")),
        ("bernese_mountain_dog", _("Bernese Mountain Dog")),
        ("bichon_frise", _("Bichon Frise")),
        ("havanese", _("Havanese")),
        ("billy", _("Billy")),
        ("black-and-tan_coonhound", _("Black-and-Tan Coonhound")),
        ("bolognese", _("Bolognese")),
        ("border_collie", _("Border Collie")),
        ("border_terrier", _("Border Terrier")),
        ("bosnian_coarsehaired_hound", _("Bosnian Coarsehaired Hound")),
        ("boston_terrier", _("Boston Terrier")),
        ("french_bulldog", _("French Bulldog")),
        ("bouvier_des_ardennes", _("Bouvier des Ardennes")),
        ("bouvier_des_flandres", _("Bouvier des Flandres")),
        ("italian_pointer", _("Italian Pointer")),
        ("austrian_black-and-tan_hound", _("Austrian Black-and-Tan Hound")),
        ("ariege_pointer", _("Ariege Pointer")),
        ("auvergne_pointer", _("Auvergne Pointer")),
        ("bourbonnais_pointer", _("Bourbonnais Pointer")),
        ("french_pointer)_gascogne_type_(large)", _("French Pointer, Gascogne type (Large)")),
        ("french_pointer)_pyrenean_type_(small)", _("French Pointer, Pyrenean type (Small)")),
        ("saint-germain_pointer", _("Saint-Germain Pointer")),
        ("medium_griffon_vendeen", _("Medium Griffon Vendeen")),
        ("broholmer", _("Broholmer")),
        ("bull_terrier", _("Bull Terrier")),
        ("bulldog", _("Bulldog")),
        ("bullmastiff", _("Bullmastiff")),
        ("majorca_shepherd_dog", _("Majorca Shepherd Dog")),
        ("majorca_mastiff", _("Majorca Mastiff")),
        ("cairn_terrier", _("Cairn Terrier")),
        ("canaan_dog", _("Canaan Dog")),
        ("italian_corso_dog", _("Italian Corso Dog")),
        ("bergamasco_shepherd", _("Bergamasco Shepherd")),
        ("maremma-abruzzes_sheepdog", _("Maremma-Abruzzes Sheepdog")),
        ("poodle", _("Poodle")),
        ("portuguese_water_dog", _("Portuguese Water Dog")),
        ("castro_laboreiro_dog", _("Castro Laboreiro Dog")),
        ("saint_miguel_cattle_dog", _("Saint Miguel Cattle Dog")),
        ("portuguese_sheepdog", _("Portuguese Sheepdog")),
        ("estrela_mountain_dog", _("Estrela Mountain Dog")),
        ("cavalier_king_charles_spaniel", _("Cavalier King Charles Spaniel")),
        ("czechoslovakian_wolfdog", _("Czechoslovakian Wolfdog")),
        ("bohemian_wirehaired_pointing_griffon", _("Bohemian Wirehaired Pointing Griffon")),
        ("cesky_terrier", _("Cesky Terrier")),
        ("polish_greyhound", _("Polish Greyhound")),
        ("chesapeake_bay_retriever", _("Chesapeake Bay Retriever")),
        ("artois_hound", _("Artois Hound")),
        ("belgian_shepherd_dog", _("Belgian Shepherd Dog")),
        ("pyrenean_sheepdog)_smooth-faced", _("Pyrenean Sheepdog, Smooth-faced")),
        ("pyrenean_sheepdog)_longhaired", _("Pyrenean Sheepdog, Longhaired")),
        ("pyrenean_mountain_dog", _("Pyrenean Mountain Dog")),
        ("bloodhound", _("Bloodhound")),
        ("chihuahua", _("Chihuahua")),
        ("japanese_chin", _("Japanese Chin")),
        ("chinese_crested_dog", _("Chinese Crested Dog")),
        ("chow_chow", _("Chow Chow")),
        ("uruguayan_cimarron", _("Uruguayan Cimarron")),
        ("southeastern_european_shepherd", _("Southeastern European Shepherd")),
        ("romanian_carpathian_shepherd_dog", _("Romanian Carpathian Shepherd Dog")),
        ("romanian_mioritic_shepherd_dog", _("Romanian Mioritic Shepherd Dog")),
        ("cirneco_dell'etna", _("Cirneco dell'Etna")),
        ("clumber_spaniel", _("Clumber Spaniel")),
        ("anatolian_shepherd_dog", _("Anatolian Shepherd Dog")),
        ("collie)_rough", _("Collie, Rough")),
        ("collie)_smooth", _("Collie, Smooth")),
        ("coton_de_tulear", _("Coton de Tulear")),
        ("montenegrin_mountain_hound", _("Montenegrin Mountain Hound")),
        ("curly_coated_retriever", _("Curly Coated Retriever")),
        ("dachshund", _("Dachshund")),
        ("dalmatian", _("Dalmatian")),
        ("dandie_dinmont_terrier", _("Dandie Dinmont Terrier")),
        ("danish-swedish_farmdog", _("Danish-Swedish Farmdog")),
        ("deerhound", _("Deerhound")),
        ("german_wirehaired_pointer", _("German Wirehaired Pointer")),
        ("german_shorthaired_pointer", _("German Shorthaired Pointer")),
        ("german_longhaired_pointer", _("German Longhaired Pointer")),
        ("german_rough-haired_pointer", _("German Rough-haired Pointer")),
        ("german_hound", _("German Hound")),
        ("great_dane", _("Great Dane")),
        ("boxer", _("Boxer")),
        ("german_hunting_terrier", _("German Hunting Terrier")),
        ("german_pinscher", _("German Pinscher")),
        ("german_shepherd_dog", _("German Shepherd Dog")),
        ("german_spitz", _("German Spitz")),
        ("german_spaniel", _("German Spaniel")),
        ("tibetan_mastiff", _("Tibetan Mastiff")),
        ("dobermann", _("Dobermann")),
        ("dogo_argentino", _("Dogo Argentino")),
        ("dogo_canario", _("Dogo Canario")),
        ("dogue_de_bordeaux", _("Dogue de Bordeaux")),
        ("drentsche_partridge_dog", _("Drentsche Partridge Dog")),
        ("drever", _("Drever")),
        ("hungarian_wirehaired_pointer", _("Hungarian Wirehaired Pointer")),
        ("norwegian_hound", _("Norwegian Hound")),
        ("english_cocker_spaniel", _("English Cocker Spaniel")),
        ("english_foxhound", _("English Foxhound")),
        ("english_pointer", _("English Pointer")),
        ("english_setter", _("English Setter")),
        ("english_springer_spaniel", _("English Springer Spaniel")),
        ("english_toy_terrier_(english_black-and-tan_terrier)",
         _("English Toy Terrier (English Black-and-Tan Terrier)")),
        ("entlebuch_cattle_dog", _("Entlebuch Cattle Dog")),
        ("blue_picardy_spaniel", _("Blue Picardy Spaniel")),
        ("brittany_spaniel", _("Brittany Spaniel")),
        ("french_spaniel", _("French Spaniel")),
        ("continental_toy_spaniel", _("Continental Toy Spaniel")),
        ("picardy_spaniel", _("Picardy Spaniel")),
        ("pont-audemer_spaniel", _("Pont-Audemer Spaniel")),
        ("transylvanian_hound", _("Transylvanian Hound")),
        ("eurasian", _("Eurasian")),
        ("field_spaniel", _("Field Spaniel")),
        ("fila_brasileiro", _("Fila Brasileiro")),
        ("flat_coated_retriever", _("Flat Coated Retriever")),
        ("fox_terrier)_smooth", _("Fox Terrier, Smooth")),
        ("fox_terrier)_wire", _("Fox Terrier, Wire")),
        ("french_white-and-black_hound", _("French White-and-Black Hound")),
        ("french_white-and-orange_hound", _("French White-and-Orange Hound")),
        ("french_tricolour_hound", _("French Tricolour Hound")),
        ("spanish_greyhound", _("Spanish Greyhound")),
        ("old_danish_pointer", _("Old Danish Pointer")),
        ("gascon_saintongeois", _("Gascon Saintongeois")),
        ("golden_retriever", _("Golden Retriever")),
        ("polish_hunting_dog", _("Polish Hunting Dog")),
        ("gordon_setter", _("Gordon Setter")),
        ("catalan_sheepdog", _("Catalan Sheepdog")),
        ("great_anglo-french_white-and-black_hound", _("Great Anglo-French White-and-Black Hound")),
        ("great_anglo-french_white-and-orange_hound", _("Great Anglo-French White-and-Orange Hound")),
        ("great_anglo-french_tricolour_hound", _("Great Anglo-French Tricolour Hound")),
        ("grand_basset_griffon_vendeen", _("Grand Basset Griffon Vendeen")),
        ("great_gascony_blue", _("Great Gascony Blue")),
        ("grand_griffon_vendeen", _("Grand Griffon Vendeen")),
        ("greyhound", _("Greyhound")),
        ("wirehaired_pointing_griffon_korthals", _("Wirehaired Pointing Griffon Korthals")),
        ("griffon_belge", _("Griffon Belge")),
        ("blue_gascony_griffon", _("Blue Gascony Griffon")),
        ("griffon_bruxellois", _("Griffon Bruxellois")),
        ("fawn_brittany_griffon", _("Fawn Brittany Griffon")),
        ("griffon_nivernais", _("Griffon Nivernais")),
        ("greenland_dog", _("Greenland Dog")),
        ("large_munsterlander", _("Large Munsterlander")),
        ("great_swiss_mountain_dog", _("Great Swiss Mountain Dog")),
        ("halden_hound", _("Halden Hound")),
        ("hamiltonstovare", _("Hamiltonstovare")),
        ("hanoverian_scenthound", _("Hanoverian Scenthound")),
        ("harrier", _("Harrier")),
        ("hellenic_hound", _("Hellenic Hound")),
        ("hokkaido", _("Hokkaido")),
        ("dutch_shepherd_dog", _("Dutch Shepherd Dog")),
        ("dutch_smoushond", _("Dutch Smoushond")),
        ("hovawart", _("Hovawart")),
        ("croatian_shepherd_dog", _("Croatian Shepherd Dog")),
        ("hygen_hound", _("Hygen Hound")),
        ("south_russian_shepherd_dog", _("South Russian Shepherd Dog")),
        ("irish_glen_of_imaal_terrier", _("Irish Glen of Imaal Terrier")),
        ("irish_red_setter", _("Irish Red Setter")),
        ("irish_red_and_white_setter", _("Irish Red and White Setter")),
        ("irish_soft_coated_wheaten_terrier", _("Irish Soft Coated Wheaten Terrier")),
        ("irish_terrier", _("Irish Terrier")),
        ("irish_water_spaniel", _("Irish Water Spaniel")),
        ("irish_wolfhound", _("Irish Wolfhound")),
        ("icelandic_sheepdog", _("Icelandic Sheepdog")),
        ("istrian_shorthaired_scenthound", _("Istrian Shorthaired Scenthound")),
        ("istrian_wirehaired_scenthound", _("Istrian Wirehaired Scenthound")),
        ("jack_russell_terrier", _("Jack Russell Terrier")),
        ("jamthund", _("Jamthund")),
        ("yugoslavian_shepherd_dog_(sharplanina)", _("Yugoslavian Shepherd Dog (Sharplanina)")),
        ("kai", _("Kai")),
        ("karelian_bear_dog", _("Karelian Bear Dog")),
        ("caucasian_shepherd_dog", _("Caucasian Shepherd Dog")),
        ("kerry_blue_terrier", _("Kerry Blue Terrier")),
        ("king_charles_spaniel", _("King Charles Spaniel")),
        ("kishu", _("Kishu")),
        ("small_munsterlander", _("Small Munsterlander")),
        ("komondor", _("Komondor")),
        ("korea_jindo_dog", _("Korea Jindo Dog")),
        ("karst_shepherd_dog", _("Karst Shepherd Dog")),
        ("kromfohrlander", _("Kromfohrlander")),
        ("kuvasz", _("Kuvasz")),
        ("labrador_retriever", _("Labrador Retriever")),
        ("romagna_water_dog", _("Romagna Water Dog")),
        ("lakeland_terrier", _("Lakeland Terrier")),
        ("lancashire_heeler", _("Lancashire Heeler")),
        ("landseer)", _("Landseer,")),
        ("lapponian_herder", _("Lapponian Herder")),
        ("leonberger", _("Leonberger")),
        ("lhasa_apso", _("Lhasa Apso")),
        ("hungarian_greyhound", _("Hungarian Greyhound")),
        ("maltese", _("Maltese")),
        ("manchester_terrier", _("Manchester Terrier")),
        ("mastiff", _("Mastiff")),
        ("spanish_mastiff", _("Spanish Mastiff")),
        ("pyrenean_mastiff", _("Pyrenean Mastiff")),
        ("neapolitan_mastiff", _("Neapolitan Mastiff")),
        ("miniature_bull_terrier", _("Miniature Bull Terrier")),
        ("mudi", _("Mudi")),
        ("kooikerhondje", _("Kooikerhondje")),
        ("dutch_schapendoes", _("Dutch Schapendoes")),
        ("newfoundland", _("Newfoundland")),
        ("japanese_spitz", _("Japanese Spitz")),
        ("japanese_terrier", _("Japanese Terrier")),
        ("norfolk_terrier", _("Norfolk Terrier")),
        ("norrbottenspitz", _("Norrbottenspitz")),
        ("norwegian_buhund", _("Norwegian Buhund")),
        ("norwegian_elkhound_grey", _("Norwegian Elkhound Grey")),
        ("norwegian_elkhound_black", _("Norwegian Elkhound Black")),
        ("norwegian_lundehund", _("Norwegian Lundehund")),
        ("norwich_terrier", _("Norwich Terrier")),
        ("nova_scotia_duck_tolling_retriever", _("Nova Scotia Duck Tolling Retriever")),
        ("polish_hound", _("Polish Hound")),
        ("old_english_sheepdog_(bobtail)", _("Old English Sheepdog (Bobtail)")),
        ("austrian_pinscher", _("Austrian Pinscher")),
        ("otterhound", _("Otterhound")),
        ("parson_russell_terrier", _("Parson Russell Terrier")),
        ("pekingese", _("Pekingese")),
        ("burgos_pointer", _("Burgos Pointer")),
        ("portuguese_pointer", _("Portuguese Pointer")),
        ("spanish_water_dog", _("Spanish Water Dog")),
        ("peruvian_hairless_dog", _("Peruvian Hairless Dog")),
        ("petit_basset_griffon_vendeen", _("Petit Basset Griffon Vendeen")),
        ("small_gascony_blue", _("Small Gascony Blue")),
        ("petit_brabançon", _("Petit Brabançon")),
        ("little_lion_dog", _("Little Lion Dog")),
        ("pharaoh_hound", _("Pharaoh Hound")),
        ("italian_greyhound", _("Italian Greyhound")),
        ("canarian_warren_hound_(canarian_podenco)", _("Canarian Warren Hound (Canarian Podenco)")),
        ("ibizan_hound", _("Ibizan Hound")),
        ("portuguese_warren_hound_(portuguese_podengo)", _("Portuguese Warren Hound (Portuguese Podengo)")),
        ("poitevin", _("Poitevin")),
        ("polish_lowland_sheepdog", _("Polish Lowland Sheepdog")),
        ("tatra_shepherd_dog", _("Tatra Shepherd Dog")),
        ("porcelaine", _("Porcelaine")),
        ("save_valley_scenthound", _("Save Valley Scenthound")),
        ("pudelpointer", _("Pudelpointer")),
        ("pug", _("Pug")),
        ("puli", _("Puli")),
        ("pumi", _("Pumi")),
        ("rafeiro_of_alentejo", _("Rafeiro of Alentejo")),
        ("rhodesian_ridgeback", _("Rhodesian Ridgeback")),
        ("giant_schnauzer", _("Giant Schnauzer")),
        ("rottweiler", _("Rottweiler")),
        ("hungarian_shorthaired_pointer", _("Hungarian Shorthaired Pointer")),
        ("russian_hunting_sighthound_(borzoi)", _("Russian Hunting Sighthound (Borzoi)")),
        ("russian_black_terrier", _("Russian Black Terrier")),
        ("russian_toy", _("Russian Toy")),
        ("russian-european_laika", _("Russian-European Laika")),
        ("saarloos_wolfdog", _("Saarloos Wolfdog")),
        ("spanish_hound", _("Spanish Hound")),
        ("saint_bernard", _("Saint Bernard")),
        ("saluki", _("Saluki")),
        ("samoyed", _("Samoyed")),
        ("schillerstovare", _("Schillerstovare")),
        ("schipperke", _("Schipperke")),
        ("schnauzer", _("Schnauzer")),
        ("swiss_hound", _("Swiss Hound")),
        ("small_swiss_hound", _("Small Swiss Hound")),
        ("scottish_terrier", _("Scottish Terrier")),
        ("sealyham_terrier", _("Sealyham Terrier")),
        ("italian_hound)_rough-haired", _("Italian Hound, Rough-haired")),
        ("italian_hound)_shorthaired", _("Italian Hound, Shorthaired")),
        ("shar_pei", _("Shar Pei")),
        ("shetland_sheepdog", _("Shetland Sheepdog")),
        ("shiba", _("Shiba")),
        ("shih_tzu", _("Shih Tzu")),
        ("shikoku", _("Shikoku")),
        ("siberian_husky", _("Siberian Husky")),
        ("skye_terrier", _("Skye Terrier")),
        ("arabian_greyhound", _("Arabian Greyhound")),
        ("slovakian_chuvach", _("Slovakian Chuvach")),
        ("wirehaired_slovakian_pointer", _("Wirehaired Slovakian Pointer")),
        ("slovakian_hound", _("Slovakian Hound")),
        ("smalandsstovare", _("Smalandsstovare")),
        ("spinone", _("Spinone")),
        ("central_asia_shepherd_dog", _("Central Asia Shepherd Dog")),
        ("serbian_hound", _("Serbian Hound")),
        ("serbian_tricolour_hound", _("Serbian Tricolour Hound")),
        ("frisian_pointer", _("Frisian Pointer")),
        ("staffordshire_bull_terrier", _("Staffordshire Bull Terrier")),
        ("styrian_coarsehaired_hound", _("Styrian Coarsehaired Hound")),
        ("finnish_hound", _("Finnish Hound")),
        ("finnish_lapphund", _("Finnish Lapphund")),
        ("finnish_spitz", _("Finnish Spitz")),
        ("sussex_spaniel", _("Sussex Spaniel")),
        ("swedish_lapphund", _("Swedish Lapphund")),
        ("taiwan_dog", _("Taiwan Dog")),
        ("brazilian_terrier", _("Brazilian Terrier")),
        ("thai_bangkaew_dog", _("Thai Bangkaew Dog")),
        ("thai_ridgeback_dog", _("Thai Ridgeback Dog")),
        ("tibetan_spaniel", _("Tibetan Spaniel")),
        ("tibetan_terrier", _("Tibetan Terrier")),
        ("tyrolean_hound", _("Tyrolean Hound")),
        ("bosnian_and_herzegovinian-croatian_shepherd_dog", _("Bosnian and Herzegovinian-Croatian Shepherd Dog")),
        ("tosa", _("Tosa")),
        ("swedish_vallhund", _("Swedish Vallhund")),
        ("italian_volpino", _("Italian Volpino")),
        ("east_siberian_laika", _("East Siberian Laika")),
        ("weimaraner", _("Weimaraner")),
        ("welsh_corgi_cardigan", _("Welsh Corgi Cardigan")),
        ("welsh_corgi_pembroke", _("Welsh Corgi Pembroke")),
        ("welsh_springer_spaniel", _("Welsh Springer Spaniel")),
        ("welsh_terrier", _("Welsh Terrier")),
        ("west_highland_white_terrier", _("West Highland White Terrier")),
        ("westphalian_dachsbracke", _("Westphalian Dachsbracke")),
        ("frisian_water_dog", _("Frisian Water Dog")),
        ("whippet", _("Whippet")),
        ("xoloitzcuintle", _("Xoloitzcuintle")),
        ("yorkshire_terrier", _("Yorkshire Terrier")),
        ("west_siberian_laika", _("West Siberian Laika")),
        ("miniature_pinscher", _("Miniature Pinscher")),
        ("miniature_schnauzer", _("Miniature Schnauzer")),
    )

    CATS_CHOICES = ()

    title = models.CharField(max_length=255, null=True, blank=True, choices=DOGS_CHOICES + CATS_CHOICES)
    type = models.CharField(max_length=255, null=True, blank=True, choices=Kennel.TYPE_CHOICES)

    history = models.CharField(max_length=65535, null=True, blank=True)
    character = models.CharField(max_length=65535, null=True, blank=True)
    standard = models.CharField(max_length=65535, null=True, blank=True)
    club = models.CharField(max_length=255, null=True, blank=True)
    slug = models.CharField(max_length=65535, null=True, blank=True)

    class Meta:
        db_table = 'animal_breeds'
        verbose_name = 'Breed'
        verbose_name_plural = 'Breeds'

    def humanize_title(self):
        return dict(self.DOGS_CHOICES + self.CATS_CHOICES).get(self.title)

    def __str__(self):
        return u'%s' % dict(self.DOGS_CHOICES + self.CATS_CHOICES).get(self.title)
