# Generated by Django 2.0.6 on 2018-06-08 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kennel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, choices=[('dogs', 'dogs'), ('cats', 'cats')], default='dogs', max_length=100, null=True)),
                ('reg_number', models.CharField(blank=True, max_length=50, null=True)),
                ('about', models.CharField(blank=True, max_length=10000, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='kennels/covers/%Y/%m/%d')),
                ('slug', models.CharField(blank=True, max_length=256, null=True)),
                ('address', models.CharField(blank=True, max_length=1024, null=True)),
                ('skype', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('site', models.URLField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
