# Generated by Django 2.0.6 on 2018-06-14 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20180613_1411'),
        ('kennels', '0002_auto_20180611_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='kennel',
            name='country_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.CountryClub'),
        ),
    ]
