# Generated by Django 2.0.6 on 2018-06-15 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('countries', '0003_auto_20180614_1023'),
        ('kennels', '0003_kennel_country_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='kennel',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='countries.Country'),
        ),
        migrations.AddField(
            model_name='kennel',
            name='timezone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='kennel',
            table='kennels',
        ),
    ]
