# Generated by Django 2.0.6 on 2018-06-25 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kennels', '0004_auto_20180615_1539'),
        ('animals', '0001_initial'),
        ('breeds', '0002_auto_20180614_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Litter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('litter', models.CharField(blank=True, max_length=256, null=True)),
                ('birthday', models.CharField(blank=True, max_length=100, null=True)),
                ('pedigree', models.URLField(blank=True, max_length=2048, null=True)),
                ('males', models.IntegerField(blank=True, null=True)),
                ('females', models.IntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/photo/%Y/%m/%d')),
                ('about', models.CharField(blank=True, max_length=10000, null=True)),
                ('slug', models.CharField(blank=True, max_length=256, null=True)),
                ('breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='breeds.Breed')),
                ('dam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dam_animal', to='animals.BaseAnimal')),
                ('kennel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kennel_of_birth', to='kennels.Kennel')),
                ('sir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sir_animal', to='animals.BaseAnimal')),
            ],
            options={
                'verbose_name': 'Litter',
                'verbose_name_plural': 'Litters',
                'db_table': 'kennel_litter',
            },
        ),
    ]
