# Generated by Django 2.0.6 on 2018-06-13 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubsAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, choices=[('dogs', 'dogs'), ('cats', 'cats')], default='dogs', max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Clubs Association',
                'verbose_name_plural': 'Clubs Associations',
                'db_table': 'clubs_associations',
            },
        ),
        migrations.CreateModel(
            name='CountryClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('dogs', 'dogs'), ('cats', 'cats')], default='dogs', max_length=64, null=True)),
                ('club_association', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.CountryClub')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_of_origin', to='countries.Country')),
            ],
            options={
                'verbose_name': 'Country Club',
                'verbose_name_plural': 'Country Clubs',
                'db_table': 'country_clubs',
            },
        ),
    ]
