from django.db import models

# -*- coding: utf-8 -*-
from django.db import models
from django.utils.translation import ugettext_lazy as _

from base.models import BaseModel


class Country(BaseModel):
    COUNTRY_TITLES = (
        ("afghanistan", _(u"Afghanistan")),
        ("aland_islands", _(u"Aland Islands")),
        ("albania", _(u"Albania")),
        ("algeria", _(u"Algeria")),
        ("american_samoa", _(u"American Samoa")),
        ("andorra", _(u"Andorra")),
        ("angola", _(u"Angola")),
        ("anguilla", _(u"Anguilla")),
        ("antarctica", _(u"Antarctica")),
        ("antigua_and_barbuda", _(u"Antigua and Barbuda")),
        ("argentina", _(u"Argentina")),
        ("armenia", _(u"Armenia")),
        ("aruba", _(u"Aruba")),
        ("australia", _(u"Australia")),
        ("austria", _(u"Austria")),
        ("azerbaijan", _(u"Azerbaijan")),
        ("bahamas", _(u"Bahamas")),
        ("bahrain", _(u"Bahrain")),
        ("bangladesh", _(u"Bangladesh")),
        ("barbados", _(u"Barbados")),
        ("belarus", _(u"Belarus")),
        ("belgium", _(u"Belgium")),
        ("belize", _(u"Belize")),
        ("benin", _(u"Benin")),
        ("bermuda", _(u"Bermuda")),
        ("bhutan", _(u"Bhutan")),
        ("bolivia", _(u"Plurinational State of Bolivia")),
        ("bonaire", _(u"Bonaire")),
        ("bosnia_and_herzegovina", _(u"Bosnia and Herzegovina")),
        ("botswana", _(u"Botswana")),
        ("bouvet_island", _(u"Bouvet Island")),
        ("brazil", _(u"Brazil")),
        ("british_indian_ocean_territory", _(u"British Indian Ocean Territory")),
        ("brunei_darussalam", _(u"Brunei Darussalam")),
        ("bulgaria", _(u"Bulgaria")),
        ("burkina_faso", _(u"Burkina Faso")),
        ("burundi", _(u"Burundi")),
        ("cambodia", _(u"Cambodia")),
        ("cameroon", _(u"Cameroon")),
        ("canada", _(u"Canada")),
        ("cape_verde", _(u"Cape Verde")),
        ("cayman_islands", _(u"Cayman Islands")),
        ("central_african_republic", _(u"Central African Republic")),
        ("chad", _(u"Chad")),
        ("chile", _(u"Chile")),
        ("china", _(u"China")),
        ("christmas_island", _(u"Christmas Island")),
        ("cocos_(keeling)_islands", _(u"Cocos (Keeling) Islands")),
        ("colombia", _(u"Colombia")),
        ("comoros", _(u"Comoros")),
        ("congo", _(u"Congo")),
        ("democratic_republic_of_the_congo", _(u"Democratic Republic of the Congo")),
        ("cook_islands", _(u"Cook Islands")),
        ("costa_rica", _(u"Costa Rica")),
        ("cote_divoire", _(u"Cote d'Ivoire")),
        ("croatia", _(u"Croatia")),
        ("cuba", _(u"Cuba")),
        ("curacao", _(u"Curacao")),
        ("cyprus", _(u"Cyprus")),
        ("czech_republic", _(u"Czech Republic")),
        ("denmark", _(u"Denmark")),
        ("djibouti", _(u"Djibouti")),
        ("dominica", _(u"Dominica")),
        ("dominican_republic", _(u"Dominican Republic")),
        ("ecuador", _(u"Ecuador")),
        ("egypt", _(u"Egypt")),
        ("el_salvador", _(u"El Salvador")),
        ("equatorial_guinea", _(u"Equatorial Guinea")),
        ("eritrea", _(u"Eritrea")),
        ("estonia", _(u"Estonia")),
        ("ethiopia", _(u"Ethiopia")),
        ("falkland_islands_(malvinas)", _(u"Falkland Islands (Malvinas)")),
        ("faroe_islands", _(u"Faroe Islands")),
        ("fiji", _(u"Fiji")),
        ("finland", _(u"Finland")),
        ("france", _(u"France")),
        ("french_guiana", _(u"French Guiana")),
        ("french_polynesia", _(u"French Polynesia")),
        ("french_southern_territories", _(u"French Southern Territories")),
        ("gabon", _(u"Gabon")),
        ("gambia", _(u"Gambia")),
        ("georgia", _(u"Georgia")),
        ("germany", _(u"Germany")),
        ("ghana", _(u"Ghana")),
        ("gibraltar", _(u"Gibraltar")),
        ("greece", _(u"Greece")),
        ("greenland", _(u"Greenland")),
        ("grenada", _(u"Grenada")),
        ("guadeloupe", _(u"Guadeloupe")),
        ("guam", _(u"Guam")),
        ("guatemala", _(u"Guatemala")),
        ("guernsey", _(u"Guernsey")),
        ("guinea", _(u"Guinea")),
        ("guinea-bissau", _(u"Guinea-Bissau")),
        ("guyana", _(u"Guyana")),
        ("haiti", _(u"Haiti")),
        ("heard_island_and_mcdonald_islands", _(u"Heard Island and McDonald Islands")),
        ("holy_see_(vatican_city_state)", _(u"Holy See (Vatican City State)")),
        ("honduras", _(u"Honduras")),
        ("hong_kong", _(u"Hong Kong")),
        ("hungary", _(u"Hungary")),
        ("iceland", _(u"Iceland")),
        ("india", _(u"India")),
        ("indonesia", _(u"Indonesia")),
        ("iran", _(u"Islamic Republic of Iran")),
        ("iraq", _(u"Iraq")),
        ("ireland", _(u"Ireland")),
        ("isle_of_man", _(u"Isle of Man")),
        ("israel", _(u"Israel")),
        ("italy", _(u"Italy")),
        ("jamaica", _(u"Jamaica")),
        ("japan", _(u"Japan")),
        ("jersey", _(u"Jersey")),
        ("jordan", _(u"Jordan")),
        ("kazakhstan", _(u"Kazakhstan")),
        ("kenya", _(u"Kenya")),
        ("kiribati", _(u"Kiribati")),
        ("democratic_peoples_republic_of_korea", _(u"Democratic People's Republic of Korea")),
        ("republic_of_korea", _(u"Republic of Korea")),
        ("kuwait", _(u"Kuwait")),
        ("kyrgyzstan", _(u"Kyrgyzstan")),
        ("lao_peoples_democratic_republic", _(u"Lao People's Democratic Republic")),
        ("latvia", _(u"Latvia")),
        ("lebanon", _(u"Lebanon")),
        ("lesotho", _(u"Lesotho")),
        ("liberia", _(u"Liberia")),
        ("libya", _(u"Libya")),
        ("liechtenstein", _(u"Liechtenstein")),
        ("lithuania", _(u"Lithuania")),
        ("luxembourg", _(u"Luxembourg")),
        ("macao", _(u"Macao")),
        ("macedonia", _(u"Macedonia")),
        ("madagascar", _(u"Madagascar")),
        ("malawi", _(u"Malawi")),
        ("malaysia", _(u"Malaysia")),
        ("maldives", _(u"Maldives")),
        ("mali", _(u"Mali")),
        ("malta", _(u"Malta")),
        ("marshall_islands", _(u"Marshall Islands")),
        ("martinique", _(u"Martinique")),
        ("mauritania", _(u"Mauritania")),
        ("mauritius", _(u"Mauritius")),
        ("mexico", _(u"Mexico")),
        ("federated_states_of_micronesia", _(u"Federated States of Micronesia")),
        ("moldova", _(u"Republic of Moldova")),
        ("monaco", _(u"Monaco")),
        ("mongolia", _(u"Mongolia")),
        ("montenegro", _(u"Montenegro")),
        ("morocco", _(u"Morocco")),
        ("mozambique", _(u"Mozambique")),
        ("myanmar", _(u"Myanmar")),
        ("namibia", _(u"Namibia")),
        ("nauru", _(u"Nauru")),
        ("nepal", _(u"Nepal")),
        ("netherlands", _(u"Netherlands")),
        ("new_caledonia", _(u"New Caledonia")),
        ("new_zealand", _(u"New Zealand")),
        ("nicaragua", _(u"Nicaragua")),
        ("niger", _(u"Niger")),
        ("nigeria", _(u"Nigeria")),
        ("niue", _(u"Niue")),
        ("norfolk_island", _(u"Norfolk Island")),
        ("northern_mariana_islands", _(u"Northern Mariana Islands")),
        ("norway", _(u"Norway")),
        ("oman", _(u"Oman")),
        ("pakistan", _(u"Pakistan")),
        ("palau", _(u"Palau")),
        ("state_of_palestine", _(u"State of Palestine")),
        ("panama", _(u"Panama")),
        ("papua_new_guinea", _(u"Papua New Guinea")),
        ("paraguay", _(u"Paraguay")),
        ("peru", _(u"Peru")),
        ("philippines", _(u"Philippines")),
        ("pitcairn", _(u"Pitcairn")),
        ("poland", _(u"Poland")),
        ("portugal", _(u"Portugal")),
        ("puerto_rico", _(u"Puerto Rico")),
        ("qatar", _(u"Qatar")),
        ("reunion", _(u"Reunion")),
        ("romania", _(u"Romania")),
        ("russian_federation", _(u"Russian Federation")),
        ("rwanda", _(u"Rwanda")),
        ("saint_barthelemy", _(u"Saint Barthelemy")),
        ("saint_helena", _(u"Saint Helena")),
        ("saint_kitts_and_nevis", _(u"Saint Kitts and Nevis")),
        ("saint_lucia", _(u"Saint Lucia")),
        ("saint_martin_(french_part)", _(u"Saint Martin (French part)")),
        ("saint_pierre_and_miquelon", _(u"Saint Pierre and Miquelon")),
        ("saint_vincent_and_the_grenadines", _(u"Saint Vincent and the Grenadines")),
        ("samoa", _(u"Samoa")),
        ("san_marino", _(u"San Marino")),
        ("sao_tome_and_principe", _(u"Sao Tome and Principe")),
        ("saudi_arabia", _(u"Saudi Arabia")),
        ("senegal", _(u"Senegal")),
        ("serbia", _(u"Serbia")),
        ("seychelles", _(u"Seychelles")),
        ("sierra_leone", _(u"Sierra Leone")),
        ("singapore", _(u"Singapore")),
        ("sint_maarten_(dutch_part)", _(u"Sint Maarten (Dutch part)")),
        ("slovakia", _(u"Slovakia")),
        ("slovenia", _(u"Slovenia")),
        ("solomon_islands", _(u"Solomon Islands")),
        ("somalia", _(u"Somalia")),
        ("south_africa", _(u"South Africa")),
        ("south_georgia_and_the_south_sandwich_islands", _(u"South Georgia and the South Sandwich Islands")),
        ("south_sudan", _(u"South Sudan")),
        ("spain", _(u"Spain")),
        ("sri_lanka", _(u"Sri Lanka")),
        ("sudan", _(u"Sudan")),
        ("suriname", _(u"Suriname")),
        ("svalbard_and_jan_mayen", _(u"Svalbard and Jan Mayen")),
        ("swaziland", _(u"Swaziland")),
        ("sweden", _(u"Sweden")),
        ("switzerland", _(u"Switzerland")),
        ("syrian_arab_republic", _(u"Syrian Arab Republic")),
        ("taiwan", _(u"Taiwan")),
        ("tajikistan", _(u"Tajikistan")),
        ("united_republic_of_tanzania", _(u"United Republic of Tanzania")),
        ("thailand", _(u"Thailand")),
        ("timor-leste", _(u"Timor-Leste")),
        ("togo", _(u"Togo")),
        ("tokelau", _(u"Tokelau")),
        ("tonga", _(u"Tonga")),
        ("trinidad_and_tobago", _(u"Trinidad and Tobago")),
        ("tunisia", _(u"Tunisia")),
        ("turkey", _(u"Turkey")),
        ("turkmenistan", _(u"Turkmenistan")),
        ("turks_and_caicos_islands", _(u"Turks and Caicos Islands")),
        ("tuvalu", _(u"Tuvalu")),
        ("uganda", _(u"Uganda")),
        ("ukraine", _(u"Ukraine")),
        ("united_arab_emirates", _(u"United Arab Emirates")),
        ("united_kingdom", _(u"United Kingdom")),
        ("united_states_of_america", _(u"United States Of America")),
        ("united_states_minor_outlying_islands", _(u"United States Minor Outlying Islands")),
        ("uruguay", _(u"Uruguay")),
        ("uzbekistan", _(u"Uzbekistan")),
        ("vanuatu", _(u"Vanuatu")),
        ("venezuela", _(u"Bolivarian Republic of Venezuela")),
        ("viet_nam", _(u"Viet Nam")),
        ("yemen", _(u"Yemen")),
        ("zambia", _(u"Zambia")),
        ("zimbabwe", _(u"Zimbabwe"))
    )

    code = models.CharField(max_length=32, blank=True, null=True)
    title = models.CharField(max_length=128, choices=COUNTRY_TITLES, blank=True, null=True)

    class Meta:
        db_table = 'countries'
        verbose_name = _('Country')
        verbose_name_plural = _('Countries')

    def __str__(self):
        return u'%s' % (dict(self.COUNTRY_TITLES).get(self.title))